easy_admin:
    design:
        form_theme:
            - "@EasyAdmin/form/bootstrap_5.html.twig"
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
    entities:
        Enrollment:
            class: App\Entity\Enrollment
        Accounting:
            class: App\Entity\Accounting
        Account:
            class: App\Entity\Account
        Season:
            class: App\Entity\Season
        User:
            class: App\Entity\User
        Licence:
            class: App\Entity\Licence
        Member:
            class: App\Entity\Member
        AccountingDocumnent:
            class: App\Entity\AccountingDocumnent
        ShopProduct:
            class: App\Entity\ShopProduct
            form:
                fields:
                    - { property: 'description', type: 'text_editor' }
    list:
        actions: ['show', 'export']
    