twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes :
            - bootstrap_5_layout.html.twig
    globals:
        app_iban: '%env(APP_IBAN)%'
        app_bic: '%env(APP_BIC)%'
when@test:
    twig:
        strict_variables: true
        
