vich_uploader:
    db_driver: orm

    mappings:
        enrollment_docs:
            uri_prefix: '%enrollment_docs%'
            upload_destination: '%kernel.project_dir%/public%enrollment_docs%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        medicalFile:
            uri_prefix: '%enrollment_docs%'
            upload_destination: '%kernel.project_dir%/public%enrollment_docs%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        accountingFile:
            uri_prefix: '%accounting_docs%'
            upload_destination: '%kernel.project_dir%/public%accounting_docs%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
