version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: mariadb:10.6
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: icd
      MYSQL_USER: root
      MYSQL_PASSWORD: rootroot
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
###< doctrine/doctrine-bundle ###

  pma:
    image: phpmyadmin/phpmyadmin
    links:
      - database:db
    ports:
      - "9080:80"
    depends_on:
      - database
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini


volumes:
###> doctrine/doctrine-bundle ###
  database:
###< doctrine/doctrine-bundle ###
